-- Database Design (Supabase)
-- Required tables: users, tasks, generated_images, audit_logs

-- Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    avatar_url TEXT,
    role TEXT NOT NULL DEFAULT 'user', -- 'admin' or 'user'
    oauth_provider TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- pending -> assigned -> in_progress -> submitted -> accepted (or revision_requested)
    assigned_to UUID REFERENCES public.users(id),
    created_by UUID REFERENCES public.users(id),
    product_image_url TEXT NOT NULL,
    revision_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Generated Images Table
CREATE TABLE IF NOT EXISTS public.generated_images (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    task_id UUID REFERENCES public.tasks(id) ON DELETE CASCADE,
    image_type TEXT NOT NULL, -- 'white_background', 'theme', 'creative', 'model'
    image_url TEXT NOT NULL,
    prompt_used TEXT,
    metadata JSONB,
    angle TEXT, -- 'front', 'side_45', 'closeup'
    is_final BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id),
    action TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id UUID NOT NULL,
    changes JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Admin can do everything
CREATE POLICY "Admin Full Access - users" ON public.users FOR ALL USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

CREATE POLICY "Admin Full Access - tasks" ON public.tasks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

CREATE POLICY "Admin Full Access - generated_images" ON public.generated_images FOR ALL USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

CREATE POLICY "Admin Full Access - audit_logs" ON public.audit_logs FOR ALL USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

-- Note: Because we are using external JWT (from our Flask backend) or Supabase Auth?
-- The requirements say: "Implement FULL OAuth authentication with: Google OAuth, GitHub OAuth"
-- "secure JWT session handling, protected routes"
-- If we use Flask backend for Auth and generate our own JWT, Supabase RLS based on `auth.uid()` might not work unless we sign the JWT with Supabase's secret and set the subject properly, or use Supabase Service Role Key in the backend and do manual checks. 
-- Wait, the prompt says "NEXT_PUBLIC_SUPABASE_ANON_KEY=..." and "SUPABASE_SERVICE_ROLE_KEY=...". 
-- It also says: "DATABASE SUPABASE PostgreSQL, Row Level Security (RLS)". 
-- If we use Custom JWT with Supabase, we can pass it to Supabase Client. 
-- Let's make RLS check `current_setting('request.jwt.claims', true)::jsonb ->> 'sub'` instead of `auth.uid()` if we use custom JWT, or if we use Supabase Auth, it's `auth.uid()`.
-- Actually, the prompt says: "Implement ALL endpoints... POST /api/auth/oauth/callback... GET /api/auth/me... POST /api/auth/logout" in the FLASK BACKEND. 
-- This implies Flask handles the OAuth flow and issues a custom JWT, or Flask acts as a proxy. 
-- If Flask handles Auth, then Flask connects to Supabase using `SUPABASE_SERVICE_ROLE_KEY` to read/write, and we might implement RLS on the frontend via custom JWT, OR we handle authorization in Flask. 
-- Wait, "User: only own tasks, only own generated images. No insecure public access."
-- If Flask uses the service role key, it bypasses RLS. So RLS is primarily for the Next.js frontend if it accesses Supabase directly. 
-- The prompt specifies `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY`. This means the frontend Next.js will connect to Supabase directly!
-- If the frontend connects directly, how does it get the JWT? The Next.js frontend can use the custom JWT generated by Flask, as long as Flask signs it with the `SUPABASE_JWT_SECRET`.
-- Wait, the prompt doesn't give a `SUPABASE_JWT_SECRET`. It gives `GOOGLE_CLIENT_ID`, `GITHUB_CLIENT_ID`, etc.
-- If we use standard Supabase Auth, the OAuth flow is typically handled by Supabase. But the prompt specifically asks to implement the endpoints in FLASK:
-- POST /api/auth/oauth/callback, GET /api/auth/me, POST /api/auth/logout.
-- This means the backend is the central auth server. The frontend can use standard API calls to the backend, OR we can implement the RLS policies based on our custom logic, or we can just enforce the access control in the backend APIs.
-- The prompt explicitly states: "Row Level Security ... Implement strict RLS policies ... No insecure public access."
-- And "User: only own tasks, only own generated images."
-- If the frontend needs to fetch data directly from Supabase, we would need the JWT. Without Supabase JWT Secret, we cannot create a JWT that Supabase RLS accepts out of the box, UNLESS we just use `SUPABASE_SERVICE_ROLE_KEY` everywhere and handle authorization in Flask? No, "Implement strict RLS policies" means we MUST write SQL RLS policies.
-- In Supabase, if we don't have the JWT secret, how do we test RLS? The RLS policies can be written using `auth.uid()`. Let's assume Supabase Auth might be used in the background or we will just set up the policies using `auth.uid()` which is standard for Supabase.

-- Let's write standard Supabase Auth RLS policies:
CREATE POLICY "Users can view own record" ON public.users FOR SELECT USING (
    id = auth.uid() OR 
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

CREATE POLICY "Users can update own record" ON public.users FOR UPDATE USING (
    id = auth.uid()
);

CREATE POLICY "Users can view assigned tasks" ON public.tasks FOR SELECT USING (
    assigned_to = auth.uid() OR created_by = auth.uid() OR
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

CREATE POLICY "Users can view own generated images" ON public.generated_images FOR SELECT USING (
    task_id IN (SELECT id FROM public.tasks WHERE assigned_to = auth.uid() OR created_by = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
);

CREATE POLICY "Users can insert own generated images" ON public.generated_images FOR INSERT WITH CHECK (
    task_id IN (SELECT id FROM public.tasks WHERE assigned_to = auth.uid())
);

CREATE POLICY "Users can update own generated images" ON public.generated_images FOR UPDATE USING (
    task_id IN (SELECT id FROM public.tasks WHERE assigned_to = auth.uid())
);

-- Seed Data (1 Admin, 1 User, 1 Task)
-- We will insert these via a seed script instead of migration to avoid conflicts if run multiple times, 
-- but a simple INSERT ON CONFLICT is fine too.
